### ISSUE TITLE
Argument parsing conflicts with Marian arguments

### ISSUE THREAD

**Issue by eu9ene** [hplt-project/OpusTrainer#39]
We use both Marian yaml configuration files and command line arguments and it appears that argparse conflicts with some Marian arguments. For example, I cannot use Marian `--log`  argument.

Here is how we integrate OpusTrainer in the Firefox training pipeline: [PR](https://github.com/mozilla/firefox-translations-training/pull/219/files#diff-bb35f759de2a7bdf31888cbc5f74a8a9fbef8792fb7ea8e0d66efea5795c3974)

Command:
```
opustrainer-train 
  --config /data/rw/evgeny/models/ru-en/opustrainer/student/config.opustrainer.yml 
  -d 
  --log-file /data/rw/evgeny/models/ru-en/opustrainer/student/opustrainer.log 
  --log-level INFO 
/data/rw/evgeny/firefox-translations-training-ci/3rd_party/marian-dev/build/marian 
  --model /data/rw/evgeny/models/ru-en/opustrainer/student/model.npz 
  -c configs/model/student.yml configs/training/student.train.yml 
  -T /data/rw/evgeny/models/ru-en/opustrainer/student/tmp 
  --vocabs /data/rw/evgeny/models/ru-en/better-teacher/vocab/vocab.spm /data/rw/evgeny/models/ru-en/better-teacher/vocab/vocab.spm 
  -w 8000 
  --devices 0 1 2 3 4 5 6 7 
  --log /data/rw/evgeny/models/ru-en/opustrainer/student/train.log 
  --valid-metrics chrf ce-mean-words bleu-detok 
  --valid-sets /data/rw/evgeny/data/ru-en/ci/original/devset.ruen.tsv 
  --valid-translation-output /data/rw/evgeny/models/ru-en/opustrainer/student/devset.out 
  --valid-log /data/rw/evgeny/models/ru-en/opustrainer/student/valid.log 
  --shuffle batches 
  --sentencepiece-alphas 0.1 
  --no-restore-corpus 
  --sharding local 
  --sync-sgd 
  --quiet-translation 
  --overwrite 
  --keep-best 
  --tsv 
  --disp-freq 1 
  --save-freq 5 
  --valid-freq 10 
  --after 10u 
  --dim-vocabs 1000 1000
```

Error:
```
usage: opustrainer-train [-h] --config CONFIG [--state STATE] [--sync] [--temporary-directory TEMPORARY_DIRECTORY] [--do-not-resume] [--no-shuffle] [--batch-size BATCH_SIZE] [--chunk-size CHUNK_SIZE] [--workers WORKERS] [--log-level LOG_LEVEL] [--log-file LOG_FILE] ...
opustrainer-train: error: ambiguous option: --log could match --log-level, --log-file
```

**Comment by jelmervdl** [comment]
Wait am I not using https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.parse_known_args ? I should and will fix that if I don't already.

Separating opustrainer args and the marian command with `--` should also work.

**Comment by eu9ene** [comment]
`--` doesn't work either. I made it work with this [fix](https://github.com/mozilla/OpusTrainer/commit/f99a6ac37d7563ad030edcf615db155c17120568) as a workaround. I can create a PR but maybe using parse_known_args would be a better approach.

**Comment by jelmervdl** [comment]
Argparse is being annoying, and I find your fix quite elegant. Mind if I just pull that in, add a couple of tests, and merge that in main?

**Comment by eu9ene** [comment]
sure, thanks!

**Comment by jelmervdl** [comment]
Unfortunately your fix didnt' seem to work in all scenarios, prefix matching was still being annoying. Disabling prefix matching did the trick for me. I added tests for it as well now.
