### ISSUE TITLE
PlaceholderTagModifier uses whitespace tokenizers for the initial tokenization

### ISSUE THREAD

**Issue by gregtatum** [hplt-project/OpusTrainer#56]
`PlaceholderTagModifier` uses whitespace tokenization for an initial tokenization. It discards tokenizations that have alignments that don't match. This could lead to lots of discarded sentences. The final retokenization does use the custom tokenizer, but I'm not 100% confident that it will always generate a valid alignment in case the subword tokenization changes.
 
https://github.com/hplt-project/OpusTrainer/blob/c966d7b353d6b3c6a09d9573f1ab6ba3221c1d21/src/opustrainer/modifiers/placeholders.py#L300-L307

Just using a whitespace tokenizer is also problematic for non-whitespace segmented languages.

**Comment by eu9ene** [comment]
@gregtatum it was discussed here https://github.com/hplt-project/OpusTrainer/issues/38. We're switching to space-tokenized alignments that will be later remapped by Tags modifier using spm_vocab for the student model.

**Comment by gregtatum** [comment]
Ohhh, ok now I'm understanding this problem. Thanks for the explanation.
