### ISSUE TITLE
Add word corruptor filter

### ISSUE THREAD

**Issue by XapaJIaMnu** [hplt-project/OpusTrainer#8]
Placeholder issue, to keep track of the idea:

To make the models more robust, we should introduce misspellings in some words on the source side.

**Comment by jelmervdl** [comment]
You know it's kind of funny that one of the features of Bifixer is fixing common spelling mistakes and typos 😅. We'd still definitely want this for the target side, but source side we could start off with not fixing them.

Otoh if we fix them, then we can corrupt them to different degrees in different stages during training.

Maybe we can even use [their lists](https://github.com/bitextor/bifixer/tree/master/src/bifixer/replacements) for additional (controlled) corruption?

A quick search gave me https://github.com/ranvijaykumar/typo which could be an interesting start. It currently only has the layout for English in there, and I have no idea about speed. But it does the fat finger simulation you mentioned yesterday.

**Comment by XapaJIaMnu** [comment]
I think that bifixer's lists should be definitely used, but maybe we always want to run bifixer first so that we don't have TOO MANY typos initially.

Controlled typology is better. This sounds exactly what we are looking for https://github.com/ranvijaykumar/typo
Similar Char would be really good for twitter text or y0uth 1337 5P33k. It shouldn't be too slow and it should be applicable to most languages that are typed using a qwerty keyboard.

The bifixer lists also take care of English typos (of which there are tons) as well as deliberate misspellings such as the Spanish Qu* -> K* which won't be captured by the typo package.

**Comment by jelmervdl** [comment]
Maybe this is a slightly further developed library we can use: https://github.com/makcedward/nlpaug ([the text components](https://github.com/makcedward/nlpaug/blob/master/example/textual_augmenter.ipynb), at least) 

It seems a bit more heavy, but has support for languages other than English out of the box… well for the keyboard at least. Looking further into it, it might be a bit too heavy, relying on proper models for many augmentation tasks.

**Comment by XapaJIaMnu** [comment]
Probably the typo library would be enough for the initial stage of this project.

**Comment by jelmervdl** [comment]
Another one, which makes use of nlpaug, by Facebook Research: https://github.com/facebookresearch/AugLy

But again, maybe a bit _too_ much. Let's indeed first get a first version that just uses the typo lib.
